### PR TITLE
Fixes for UNSCD and server user

### PR DESCRIPTION
**Pull request by TheFurya**
* added user creation for server user
* added unscd exception for debian since service is named unscd
* rubocop fixes

### CODE REVIEW

**Comment by TheFurya** [comment]
I added another commit, since currently the only available package on centos is nscd.

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by lamont-granquist** [comment]
- shouldn't use node.override
- should conditionaly rather than always install the nscd user
- should think through the run-nscd-as-root-dont-install-user vs. run-nscd-as-nscd-and-create-user scenarios better
closing this since its been open for nearly a year and needs a rebase and a rethink

**Comment by glensc** [comment]
will you be picking yourself useful changes from here?

**Pull request closed without merging**
